[general]
live_config_reload = true
# https://alacritty.org/config-alacritty.html
import = [
  "~/.config/alacritty/lib/font.toml",
  "~/.config/alacritty/lib/window.toml",
  "~/.config/alacritty/lib/colors.toml",
  "~/.config/alacritty/lib/cursor.toml",
]

# [shell]
# program = "zellij"
# args = []
