[tools]
bat = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
flutter = "latest"
fzf = "latest"
go = "latest"
helix = "latest"
lima = "latest"
neovim = "latest"
rust = "latest"
starship = "latest"
yazi = "latest"
zellij = "latest"
zoxide = "latest"
